import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/topNavbar/Navbar";
import Footer from "../components/footer/footer";
import HeaderBar from "../components/Header";
import { Toaster } from "sonner";
import Script from "next/script"; // ✅ required for GA/GTM

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DSL Limo Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <div >
        {/* ✅ Google Tag Manager (noscript) */}
        <Navbar />
        <HeaderBar />
        {children}
        <Footer />
        <Toaster position="top-right" richColors />
      </div>
  );
}
