import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/topNavbar/Navbar";
import Footer from "../components/footer/footer";
import HeaderBar from "../components/Header";
import { Toaster } from "sonner";



const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "DSL Limo Services",
    description: "Generated by create next app",
};
// gg
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >

                <Navbar />
                <HeaderBar />
                {children}
                <Footer />
 <Toaster position="top-right" richColors />

            </body>
        </html>
    );
}
