CREATE TABLE "dsl_booking" (
	"id" serial PRIMARY KEY NOT NULL,
	"payment_id" varchar(255),
	"name" varchar(255) NOT NULL,
	"email" varchar(255) NOT NULL,
	"phone_number" varchar(50) NOT NULL,
	"from_location" varchar(500) NOT NULL,
	"to_location" varchar(500) NOT NULL,
	"stops" jsonb,
	"pickup_date" varchar(50),
	"pickup_time" varchar(50),
	"return_date" varchar(50),
	"return_time" varchar(50),
	"passengers" integer,
	"luggage" integer,
	"flight_number" varchar(255),
	"airline_code" varchar(255),
	"return_flight_number" varchar(255),
	"return_airline_code" varchar(255),
	"car_type" varchar(255),
	"return_trip" boolean DEFAULT false,
	"trip_type" varchar(50),
	"hours" varchar(50),
	"distance" numeric(10, 2),
	"rear_seats" integer,
	"booster_seats" integer,
	"infant_seat" integer,
	"return_rear_seats" integer,
	"return_booster_seats" integer,
	"return_infant_seat" integer,
	"meet_greet" boolean DEFAULT false,
	"return_meet_greet" boolean DEFAULT false,
	"base_price" numeric(10, 2),
	"gratuity" numeric(10, 2),
	"tax" numeric(10, 2),
	"discount" numeric(10, 2),
	"is_meet_greet_price" numeric(10, 2),
	"rear_seat_price" numeric(10, 2),
	"infant_seat_price" numeric(10, 2),
	"booster_seat_price" numeric(10, 2),
	"return_price" numeric(10, 2),
	"is_return_meet_greet_price" numeric(10, 2),
	"return_rear_seat_price" numeric(10, 2),
	"return_infant_seat_price" numeric(10, 2),
	"return_booster_seat_price" numeric(10, 2),
	"total_price" numeric(10, 2),
	"is_airport_pickup" boolean DEFAULT false,
	"is_flight_track" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now() NOT NULL
);
