import type { Metadata } from "next";
import { Geist, Geist_Mono, Hind, Montserrat } from "next/font/google";
import "./globals.css";
import StripeProvider from "./components/StripeProvider";

// ✅ Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// ✅ Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Hind
const hind = Hind({
  variable: "--font-hind",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // add weights you need
});

// ✅ Montserrat
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // add weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hind.variable} ${montserrat.variable}`}
      >
        <StripeProvider> {children}</StripeProvider>

      </body>
    </html>
  );
}
